### ISSUE TITLE
cvs.points provides different results depending of scale with span

### ISSUE THREAD

**Issue by Boorhin** [holoviz/datashader#1041]
#### ALL software version info
Tested on python3.8 and jupyter notebook
gcsfs==2021.11.1
xarray[complete]==0.20.2
datashader==0.11.1
colorcet==3.0.0
numpy==1.18.1

#### Description of expected behavior and the observed behavior
I am working with the density mapping of points in a projected environment. To scale the points to sqm I am using a factor
if I use this factor in the source data (a xarray dataset) I get different values than if I scale the span in tf.shade.
The dataset contains 1billion+ points (if that makes a difference).
Of course I would prefer to only use the span argument instead of modifying my dataset

### I would appreciate if you don't draw this dataset too many times.
``` python
from xarray import open_zarr
import numpy as np
import datashader as DS
from colorcet import fire
from datashader import transfer_functions as tf
import gcsfs

fs=gcsfs.GCSFileSystem()
ds_host=open_zarr(gcsfs.mapping.GCSMap('sealice_db/trajectories_archive.zarr/',
                gcs=fs, check=True, create=False))
subds=ds_host.sel(dict(trajectory=slice(0,1000000)))
factor = 15000 # some value to scale my counts
span=np.array([0,18]) #in counts /sqm, what I am interested in

def scale_dataset(ds_host, factor, span):
    cvs=DS.Canvas(1000,1000)
    ds_host['norm']=ds_host['copepodid']/factor
    agg=cvs.points(ds_host, x='lon',y='lat', agg=DS.count('norm'))
    return tf.shade(agg, cmap=fire, how='linear', span=span)

def scale_shade(ds_host, factor):
    cvs=DS.Canvas(1000,1000)
    agg=cvs.points(ds_host, x='lon',y='lat', agg=DS.count('copepodid'))
    return tf.shade(agg, cmap=fire, how='linear', span=span*factor)

# these 2 should give the same results?
scale_dataset(subds, factor, span)
scale_shade(subds, factor)
```
Only the scaling of the dataset seem to provide a coherent result, scaling the span doesn't
#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/9576982/151667015-33a7df2d-2af0-4998-9f95-743fb01447f1.png)

**Comment by jbednar** [comment]
That code isn't runnable for me (`Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object`), but it doesn't look like it's doing what you're expecting. Here, the scaling in `scale_dataset` won't directly affect any of the results, because you are using a `count` aggregator that ignores the scaling. With `count`, all that matters is which datapoints have a non-NaN value for the indicated column; the value itself does not matter and thus dividing values by `factor` won't directly affect the results. So both cases should construct the same aggregate (examine `agg` yourself to be sure!), and then you scale them each differently so you should be expecting to see different results like this.

**Comment by Boorhin** [comment]
Yes, you need to have a google cloud access setup. I have found out the problem as I got confused by the function DS.count. It is DS.sum I needed. For the colorscale it is supposed to be on a dark background. I just tried to make the example as minimal as possible. thanks for your answer
