### ISSUE TITLE
Visual artifacts when shading Polygons

### ISSUE THREAD

**Issue by philipc2** [holoviz/datashader#1327]
I have a `spatialpandas.GeoDataFrame` with ~600k Polygons that I am attempting to render. There are no holes or gaps between any of the polygons. 

<img width="530" alt="image" src="https://github.com/holoviz/datashader/assets/67855069/19476238-4d6f-4ad3-a70a-4a30ac0919fc">

```Python
import datashader as ds
import datashader.transfer_functions as tf

cvs = ds.Canvas(plot_width=300, plot_height=300)
agg = cvs.polygons(gdf, geometry='geometry', agg=ds.mean('temperature_500hPa'))
tf.shade(agg)
```

<img width="293" alt="image" src="https://github.com/holoviz/datashader/assets/67855069/9eaa577e-75d2-4b63-befe-34f5d0a554e6">

The same issue continues when using HoloViews (which is what I started with initially. However, using different `pixel_ratio` values seems to change the behavior of these artifacts. 

```Python
hv_polygons = hv.Polygons(gdf, vdims=['temperature_500hPa'])
(hv.operation.datashader.rasterize(hv_polygons, dynamic=False, pixel_ratio=1.0) + 
 hv.operation.datashader.rasterize(hv_polygons, dynamic=False, pixel_ratio=2.0) + 
 hv.operation.datashader.rasterize(hv_polygons, dynamic=False, pixel_ratio=4.0) + 
 hv.operation.datashader.rasterize(hv_polygons, dynamic=False, pixel_ratio=8.0)).cols(2)
```

<img width="578" alt="image" src="https://github.com/holoviz/datashader/assets/67855069/1d23ac87-bc7d-4cee-bc43-da9fee28e436">

I have tried the following to attempt to isolate the issues, but it did not change anything
* Using `geopandas` instead of `spatialpandas`
* Using `matplotlib` as a backend

Version Info
* datashader                0.16.1
* holoviews                 1.18.3
* numba                     0.59.1
* spatialpandas             0.4.10

**Comment by philipc2** [comment]
I can share the data upon request. Is there a preferred format for sharing a `GeoDataFrame` with Polygons. I assume a CSV should be good?

**Comment by jbednar** [comment]
Thanks for the report. Sounds like you're sure it's not due to rounding issues in the original data? E.g. if you zoom in on one of the areas with gaps, does the gap shrink or disappear? If so it's presumably an issue with the rendering code rather than the data.  And does the same data render without gaps in other tools, e.g. native Matplotlib?

A Parquet-based file is usually more practical than CSV, but anything that you can provide end-to-end reproducible code for reading and displaying it should be fine.

**Comment by philipc2** [comment]
> Thanks for the report. Sounds like you're sure it's not due to rounding issues in the original data? E.g. if you zoom in on one of the areas with gaps, does the gap shrink or disappear? If so it's presumably an issue with the rendering code rather than the data. And does the same data render without gaps in other tools, e.g. native Matplotlib?

Yeah, there's no `NaN` values in my original dataset. 

![image](https://github.com/holoviz/datashader/assets/67855069/bc508bdd-e555-46f4-a753-e1927dc3ff65)

I took a subset of the region surrounding a cluster of the `NaN` values and plotted the vector polygons to show what the "true" mesh should look like.

![image](https://github.com/holoviz/datashader/assets/67855069/2a36996a-2843-4f6c-b946-68a0060b7984)

**Comment by philipc2** [comment]
Here's the polygons as a parquet file. 

https://drive.google.com/file/d/12YQmrJUAZBqpAwOrFLL-urIyWbR9U_SI/view?usp=sharing

**Comment by jbednar** [comment]
Can you include the complete code to go from that file to the rendered image? Thanks.

**Comment by philipc2** [comment]
> Can you include the complete code to go from that file to the rendered image? Thanks.

Sure! Here's the code that I used (with the produced output)

```Python
import datashader as ds
import datashader.transfer_functions as tf
import geopandas as gp

gdf = gp.read_parquet("out.parquet")

cvs = ds.Canvas(plot_width=300, plot_height=300)
agg = cvs.polygons(gdf, geometry='geometry', agg=ds.mean('temperature_500hPa'))
tf.shade(agg)
```

![image](https://github.com/holoviz/datashader/assets/67855069/2f63c054-4943-4a2d-97bf-bd2652d21f07)

**Comment by jbednar** [comment]
Ok, I can reproduce the issue, and I agree it doesn't seem to be caused by gaps in the original data due to things like truncating the coordinate precision in a CSV export. The gaps at least sometimes shrink or disappear on zooming in, while I think if the gaps were in the data they would get larger on zooming in:

```python
import datashader as ds, geopandas
gdf = geopandas.read_parquet("Downloads/out.parquet")

def plot(x_range=[-135,-65], y_range=[21,59]):
    cvs = ds.Canvas(plot_width=300, plot_height=300, x_range=x_range, y_range=y_range)
    agg = cvs.polygons(gdf, geometry='geometry', agg=ds.mean('temperature_500hPa'))
    return ds.tf.shade(agg, name=str((x_range,y_range)))

ds.tf.Images(plot((-111,-100), (34,45)), 
             plot((-110,-100), (35,45)),
             plot((-109,-100), (36,45)),
             plot((-109,-101), (36,44)))
```

<img width="1100" alt="image" src="https://github.com/holoviz/datashader/assets/1695496/0c75cabe-0c3e-4001-afea-73bed5104adc">

Plus if I go all the way down to the polygons, I can't see any gaps appear:

```python
ds.tf.Images(plot((-111,-110.5),     (34,34.5)), 
             plot((-111,-110.75),    (34,34.25)),
             plot((-111,-110.9),     (34,34.1)),
             plot((-110.98,-110.96), (34.03,34.05)))
```
<img width="1093" alt="image" src="https://github.com/holoviz/datashader/assets/1695496/53a594f1-32f5-45cb-98de-d0bc31f754df">

So I think Datashader is losing precision somewhere in the polygon rendering code. Unfortunately this could be quite tricky to debug! Anyone got ideas?

**Comment by philipc2** [comment]
Thanks for getting this fixed so quickly!
