### ISSUE TITLE
Hover not showing up in dashboard.py nyc taxi example

### ISSUE THREAD

**Issue by vollkorn1982** [holoviz/datashader#252]
I'm trying to run the nyc taxi example like this:

```
python dashboard.py -c nyc_taxi.yml
```

When I move the mouse cursor over the displayed data points, no mouse hover shows up.

The hover tool symbol is showing up on the right hand side and I can check and uncheck the box which pops up, when I click on it, but that does not change anything.

Hover works fine with the examples from the bokeh package.

I am on a 64 bit Ubuntu 16.04 and have a python 3.5.2 virtualenv in which I installed the current datashader master branch from git and bokeh 0.12.3 via pip.

EDIT: datashader was installed from git master, not pip

**Comment by jbednar** [comment]
Unfortunately, the Bokeh API keeps changing, and we have not yet been able to update the dashboard example to work with the latest Bokeh.   Hover information should appear with the dashboard if you use Bokeh 0.11 (``conda install bokeh=0.11.1``), but it won't appear for any later Bokeh version up to 0.12.4.  On the other hand, hover information is working fine for the hover_layer.ipynb example, for the latest Bokeh release.  

I haven't personally looked into what the changes were or what we need to do to update the dashboard, but if you wanted to check it out, just compare the code inside dashboard.py with hover_layer.ipynb, to see if you can see what to change about dashboard.py to make it work the same way.  If you can find the problem, we'd be happy to accept a pull request for dashboard.py!  You shouldn't need to understand datashader itself to do this, just how to use bokeh, since hover_layer.ipynb already shows how to do the datashader side of the calculations.

**Comment by tommycarstensen** [comment]
@vollkorn1982 Any updates on this? Thanks.

**Comment by jbednar** [comment]
We have not investigated the dashboard in particular, but you can get hover working using HoloViews 1.7 (due for release this week) as described in issue #126.

**Comment by philippjfr** [comment]
This issue references the old Bokeh based dashboard but we've long switched to a Panel based version. In future we will use Bokeh support for colormapping so that we can use hover and colormaps properly.
