### ISSUE TITLE
Improve colors for small numbers of discrete values

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#357]
The eq_hist code works very well when there are large numbers of discrete values, such as a range of different counts per pixel, which can be mapped onto the full range of color values:

![image](https://cloud.githubusercontent.com/assets/1695496/26156380/beacca8e-3adb-11e7-8408-4db4b095a593.png)

However, when zooming into a plot like that, there is often a stage where there are only two or three distinct different numbers of counts, once things overlap only very rarely.  In these cases, the colors chosen are not very helpful -- typically nearly all points get mapped to a very dimly visible color, with a few randomly overlapping points showing up clearly: 

![image](https://cloud.githubusercontent.com/assets/1695496/26156194/2c868618-3adb-11e7-85f5-654efe86cb5e.png)

Similar issues occur with count or sum aggregations using timeseries, which often double back on themselves leaving strange artifacts at peaks:

![image](https://cloud.githubusercontent.com/assets/1695496/26156759/f7426df8-3adc-11e7-86d4-8540b9f4d413.png)

In each of these cases, the issues occur when there are only a small number of total colors being used in the image, in which case using the full dynamic range is not providing any more information, and it's actually making the data less visible, because the lower bound on the color range is usually chosen to be just barely saturated enough to be reliably visible.  The result is that nearly all data points in these cases end up just barely reliably visible, rather than being the most visible colors available (which is what a person would choose in this scenario).  

I'm not sure how best to address this, since the information how many discrete bins were non-zero is in the eq_hist function, while the colors are chosen in the shade function, but presumably something can be done here.

**Comment by fzhang00** [comment]
I'm also having this issue with my hv.Curve plots, where in some cases there are very little bins with high data points, and most pixel got mapped to lower intensity color making them not nearly not visible. 
![image](https://user-images.githubusercontent.com/4636221/27195008-dcc4f7e0-51d2-11e7-96cc-6dc5e057774d.png)

**Comment by ijstokes** [comment]
Since the shading is already dynamic, would it be feasible to establish the dynamic range and bin occupancy for a discrete and relatively low-numbered color map, then re-balance the colormap for a particular view to achieve a more uniform bin distribution, and "grounding" the bottom of the color map in something with good visibility?  I've used that kind of technique for this problem in the past, albeit under conditions where I knew exactly my dataset and the visualization I was trying to generate.

e.g.

original:

value | # of points | color
------|------------|------
1        |  100            | light blue
2        | 10               | blue
3        | 1                 | dark blue

Re-mapped:

value | # of points | color
------|------------|------
1        |  100            | blue
2        | 10               | medium dark blue
3        | 1                 | dark blue

**Comment by hsparra** [comment]
Seems reasonable to me. You can always have a flag so the user could disable that functionality.

**Comment by wmayner** [comment]
Is there a workaround I can use to achieve this until it's implemented?

**Comment by jbednar** [comment]
Maybe use just half of the colormap range?

**Comment by wmayner** [comment]
Yeah, I ended up going with setting `min_alpha=128`. Thanks!

**Comment by jbednar** [comment]
Fixed by #1055.
