### ISSUE TITLE
Processing vector data with DataShader

### ISSUE THREAD

**Issue by deeplook** [holoviz/datashader#663]
A question more than an "issue" to report here hoping that's fine, too. Otherwise please point me to the right place...

I have only installed DataShader and run examples, so far. But I see a lot of these can be considered to have some "raster character", say pixels or points on various levels, aggregated as desired, think of the NYC taxi data. What I'm missing are examples with some "vector character", think of anything that "flows" on a map, cars, animals, water, wind, etc. I've seen only the OpenSky example, so far, which _might_ fit here. Is there really nothing else?

So the question is: Is DataShader equally apt at processing vector data?

**Comment by jbednar** [comment]
At its heart, Datashader is a rasterizer: whatever you give it, it will turn it into a raster, i.e., a regular grid of values that can be mapped directly into pixels on a screen or on paper.  I'd argue that points like those in the taxi example are actually vector-like rather than raster-like; they are a set of mathematically ideal locations in a continuous, not discretized, 2D coordinate system. Only once Datashader has aggregated and rasterized those points do they have any "raster character", and the same is true for points in any vector-based drawing program like Illustrator or Inkscape.  Same goes for lines like those in the OpenSky example and any of the timeseries and trajectory examples: Datashader starts with some specification of a mathematically pure vector object, in this case specified as a connected set of continuous coordinates interpreted as line segments.  And then just as has to be done for any vector drawing program, Datashader rasterizes the continuous-coordinate objects into a grid that can be displayed on pixel-based hardware.  So I would argue that Datashader is fundamentally a vector-based graphics system, and primarily *does* process vector data, though it also accepts raster data (which it *re*-rasterizes).

Rather that raster versus vector, maybe you're trying to find ways to plot spatiotemporally varying data (whether raster or vector), as discussed in https://github.com/pyviz/datashader/issues/242?  There are a lot of things that can be done there, some of which we have examples of, and others remain to be explored.

**Comment by ppwadhwa** [comment]
I'm closing this as it looks like its been answered, but feel free to re-open if there is still an issue to be addressed.  :)
