### ISSUE TITLE
stream error in examples on python 3.7

### ISSUE THREAD

**Issue by adnan-wahab** [holoviz/datashader#828]
<img width="1116" alt="Screenshot 2019-11-08 18 16 50" src="https://user-images.githubusercontent.com/2786457/68517067-f689f980-0253-11ea-8e72-dfee1931b6ba.png">

## Description

trying to run the examples on a fresh install. running version 3.7 i get the above error which seems to be related to no python 3.8. i get errors when i try to upgrade because of incompatible versions of dependencies.

**Comment by adnan-wahab** [comment]
it looks like running the examples requires 3.8, but the default installation of conda installs 3.7 and isnt compatible wit 3.8

**Comment by jbednar** [comment]
There is definitely nothing in Datashader that requires Python 3.8, because I haven't even installed 3.8, let alone tested on it. :-)  It looks like maybe you're running streaming-aggregation.ipynb?  That example is a little neglected, not being published anywhere at present, and thus may indeed not be working.  But in any case it should be "from streamz import Stream" (note the "z"), and you'd need to install the `streamz` library for it to work.

**Comment by jbednar** [comment]
Closing as stale; please reopen if still relevant!
