### ISSUE TITLE
document support for standard cartographic projections in user_guide/Geography.html 

### ISSUE THREAD

**Issue by ebo** [holoviz/datashader#849]
most of the folks I work with in science do not use the Web Mercator, but more standard ones due to WM's known inaccuracies.  (see https://www.esri.com/arcgis-blog/products/arcgis-solutions/defense/what-does-the-nga-web-mercator-advisory-mean-for-esri-defense-and-intelligence-users/ ).  It would be a nice addition to add to the user guide in the "Project Points" section, that there are many different projections possible, and provide a link.  I will try to dig around and see if I can find a good one to use, but here is one of the first examples I pulled up:

https://rpubs.com/josezuniga/359867

**Comment by jbednar** [comment]
What the guide already says is:

> You can use GeoViews or the underlying pyproj/proj.4 libraries to perform arbitrary projections to and from a large number of different coordinate reference systems. However, for the common case of wanting to view data with latitude and longitude coordinates on top of a Web Mercator tile source such as Google Maps or OpenStreetMap, Datashader provides a simple self-contained utility lnglat_to_meters(longitude, latitude) to project your data once, before visualization.

I would have thought that this text already does convey that there are many different projections, and it already links to the proj and geoviews libraries for implementing those, while saying that the one in Datashader is important mainly because it can overlay with tile services. But if you can make that clearer, please make a PR!
