### ISSUE TITLE
datashader does not work with dtype=np.float16

### ISSUE THREAD

**Issue by jmontoyam** [holoviz/datashader#914]
Hi,

I have tried to use datashader through hvplot.image(rasterize=True), it works fine when the dtype
of the xarray is np.float64 or np.float32, but it does not work when dtype is np.float16. Here it is a tiny example than reproduce this bug:
-------------------------------------------------------------------------
import numpy as np
import xarray as xr
import hvplot.xarray

A = xr.DataArray(np.random.rand(128,64).astype(np.float16))
A.hvplot.image(rasterize=True)

-------------------------------------------------------------------------
The summary of the error message is the following:

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
[1] During: typing of argument at /home/xxxxx/.conda/envs/base_cloned/lib/python3.8/site-packages/datashader/resampling.py (482)

File "../../../../../home/xxxxx/.conda/envs/base_cloned/lib/python3.8/site-packages/datashader/resampling.py", line 482:
def _get_dimensions(src, out):
    src_w = src.shape[-1]
    ^

This error may have been caused by the following argument(s):
- argument 0: Unsupported array dtype: float16
- argument 1: Unsupported array dtype: float16

Software info:

ds.__version__: '0.10.0'
hvplot.__version__: '0.5.2'
xr.__version__: '0.15.1'
np.__version__: '1.18.1'

**Comment by jbednar** [comment]
Right; float16 is definitely not supported. Datashader uses Numba for its numerical calcuations, and [Numba does not currently support float16](https://github.com/numba/numba/issues/4402). Datashader *might* work if you define NUMBA_DISABLE_JIT=1 in your environment before starting it, which will revert to standard Python/numpy calculations instead of Numba, but doing that will be _extremely_ slow even if it works, and is also likely to need a few fixes since no one has ever tested float16 types before. For anything practical, we'll have to wait on Numba to support float16 and then we can add float16 support to Datashader.
