### ISSUE TITLE
absolute color scale for heatmaps

### ISSUE THREAD

**Issue by im281** [holoviz/datashader#931]
I would like to plot the datashader heat map colors based on an absolute user-defined scale so I can compare intensities across heat maps. Currently, the colors are relative. Is this possible?

For example, this code is relative to itself:
img = tf.set_background(tf.shade(agg, cmap=["darkblue", "darkblue","darkblue","darkblue", "darkblue","darkblue", "darkblue","darkblue","darkblue", "darkblue","darkblue", "darkblue","darkblue","darkblue", "darkblue", "darkblue","darkblue","darkblue","darkblue", "darkblue", "darkblue","darkblue","darkblue", "darkblue", "darkblue","blue", "blue", "blue","blue","blue","blue", "blue","blue", "blue", "blue", "blue", "blue", "blue", "blue","blue", "blue","blue", "blue","blue", "blue","blue", "blue",
    "blue", "blue","blue", "blue","blue", "blue","blue", "blue","lightblue","cyan", "white","yellow", "lightgreen", "orangered", "pink", "darkred"]), "black",  name="Black bg")

**Comment by jbednar** [comment]
You can use the `span` argument to `tf.shade` to set the range in data values that will be mapped to the `cmap`; e.g. `span=(0.0,1.0)` if your data is in the range 0,1.  See https://datashader.org/getting_started/Pipeline.html#Controlling-ranges-for-colormapping for details.

That's an unusual colormap you have there, with up to the 40th percentile uniformly colored darkblue, up to the 90th percentile colored blue, and a different color for each of the remaining groups of 2 percentiles.  Nobody matters but the top 10%! :-)

**Comment by im281** [comment]
Thank you for your response. My intern did this (always throw interns under the bus :) ) jk Can you send me a snippet that would have a nice contrast but also be on an absolute scale? ([0,1e9]) ?

**Comment by jbednar** [comment]
If you use `span`, you can pair that with any `cmap` you like (e.g. any of the ones from [colorcet](https://colorcet.holoviz.org)); `span` is what makes the scale absolute, not the `cmap`.  Note that I don't think `span` is compatible with the default normalization function `eq_hist`, and even if it was you'd only get an absolute starting and ending point that way; so to get the entire mapping throughout the span to be fixed then you'll also need to specify `how='linear'` or `how='log'`.

**Comment by im281** [comment]
img = tf.set_background(tf.shade(agg, cmap=["white", "blue"], name="gb 5000 120000", span=[5000, 120000], how="linear"),"black",  name="Black bg")

The first image has higher values for the signal
signal   mean =   119084.648985
whereas this image has a lower average signal yet the background is white??
signal mean = 370.810418

![DDX030_posLipidomics_EQ6546A_200517_001 mzML](https://user-images.githubusercontent.com/10081392/84939865-d47f1200-b093-11ea-9792-76868c59447d.png)

![DDX030_posLipidomics_EQ6546A_200611_006b mzML](https://user-images.githubusercontent.com/10081392/84939868-d517a880-b093-11ea-881b-4ede0fd110b4.png)

**Comment by jbednar** [comment]
See the Pipeline notebook for how colors are selected, but in this case black will only be used for pixels that have no data, i.e. are NaN (used to indicated missing data) in the aggregate array. So whether you get white or black with a command like that depends on the presence of data at that location, not on the data value.

**Comment by im281** [comment]
[first_image.zip](https://github.com/holoviz/datashader/files/4795319/first_image.zip)

Here is the data for the first image. There are no missing values. Perhaps I am missing something but thank you for your response

**Comment by jbednar** [comment]
It's not about whether the data has missing values, but about whether the _aggregate_ has missing values.  The aggregate is constructed by mapping each data point into a cell in the aggregate array and then incrementing or adding to the value in that cell. I don't have the details of how you did that (presumably `Canvas.points()` with some aggregation function like count), but in any case if none of the data points land in a certain cell, that cell remains at its initial NaN value.  Then later when `tf.shade` is called, cells that have only NaN in them are not colored using the colormap (here ranging from white to blue), instead revealing whatever the background (page) color is. Then your code is setting the background color to black, which will only matter for values that are revealing the background color, which in this case would be those cells where no data point fell. I can't debug your data here, but it looks like in one case there is data spread throughout, and in the other there is localized data?  That, or I'm confused about some other aspect of your setup. In either case, I'll close this as the original question about how to get an absolute scale has been answered.  Further discussion can occur on our [Discourse site](https://discourse.holoviz.org/c/datashader), as this is a usage issue rather than a problem being reported with Datashader itself...

**Comment by im281** [comment]
ok ty for your time
