### ISSUE TITLE
nyc taxi examples needs a meta-data update

### ISSUE THREAD

**Issue by GalAvineri** [holoviz/datashader#938]
#### Description of expected behavior and the observed behavior
I should be able to try the code shown in the [introduction](https://datashader.org/getting_started/Introduction.html).
But it seems that the current data that is provided at the [nyc taxi datasets](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page) have different columns.
Specifically, instead of 'dropoff_x' and 'dropoff_y' in Web Mercator coordinates the dataset now include 'dropoff_longitude' and 'dropoff_latitude'.

Trying to run the code in the introduction with the new data, while using longitude and latitude instead, results in a much different result.
![image](https://user-images.githubusercontent.com/23617052/86597444-664bb200-bfa4-11ea-9192-a3708e08718c.png)

Could you change the example to match the currently available data, or alternatively supply a link to a dataset that matches the existing code?

**Comment by jlstevens** [comment]
Thanks for filing an issue!

I agree that it would good to both update the dataset we ship to reflect newer data, at which point we would also use the new column names. I'll tag this as a good first issue: if we find someone willing to contribute, it would involve some simple CVS data munging as well as minor changes to the notebook.

**Comment by philippjfr** [comment]
This issue must be referencing some old version of the introduction since the current version does not talk about the dataset you are referencing. Additionally the renamed columns were deliberately transformed from lat/lon to easting/northing so that they can easily be overlaid with tile sources. I suspect the data may also have been filtered to get rid of outliers somewhere way outside of NYC.

So to reproduce you should just use `datashader.utils.lnglat_to_meters` to go from latitudes and longitudes to mercator coordinates and then filter the dataset for outliers by selecting on the rough extents of NYC.

**Comment by jlstevens** [comment]
Is this mentioned in the docs where this dataset is used? If not that might help avoid such confusion in future...
